# Site settings
title: Front End Collision
subtitle: Blog of web developer Josh Beam
email: joshua.a.beam@gmail.com
copyright: 2015 Joshua Beam
description: > # this means to ignore newlines until "baseurl:"
  Website and blog of full-stack JavaScript developer, Josh Beam.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joshbeam.github.io" # the base hostname & protocol for your site
#url: "localhost:4000"
twitter_username: joshbeam92
github_username:  joshbeam

# Build settings
markdown: kramdown

exclude:
- "bower_components"
- "bower.json"
- "node_modules"
- "package.json"
- "gulpfile.js"
- "js/src"

include:
- ".nojekyll"
